export const orders = [
    {
        'Date': "10 Oct, 2021",
        'Time': "12:37 AM",
        'MealName': "Avocado Toast",
        'OrderIDNumber': "2BTVG",
        'RestaurantName': "NU Kitchen Somerville",
        'Price': "14.46",
        'OrderStatus': "Processing",
    },
    {
        'Date': "10 Oct, 2021",
        'Time': "12:37 AM",
        'MealName': "Avocado Toast",
        'OrderIDNumber': "2BTVG",
        'RestaurantName': "NU Kitchen Somerville",
        'Price': "14.46",
        'OrderStatus': "Processing",
    },
    {
        'Date': "10 Oct, 2021",
        'Time': "12:37 AM",
        'MealName': "Avocado Toast",
        'OrderIDNumber': "2BTVG",
        'RestaurantName': "NU Kitchen Somerville",
        'Price': "14.46",
        'OrderStatus': "Completed",
    },
    {
        'Date': "10 Oct, 2021",
        'Time': "12:37 AM",
        'MealName': "Avocado Toast",
        'OrderIDNumber': "2BTVG",
        'RestaurantName': "NU Kitchen Somerville",
        'Price': "14.46",
        'OrderStatus': "Processing",
    },
    {
        'Date': "10 Oct, 2021",
        'Time': "12:37 AM",
        'MealName': "Avocado Toast",
        'OrderIDNumber': "2BTVG",
        'RestaurantName': "NU Kitchen Somerville",
        'Price': "14.46",
        'OrderStatus': "Processing",
    },
    {
        'Date': "10 Oct, 2021",
        'Time': "12:37 AM",
        'MealName': "Avocado Toast",
        'OrderIDNumber': "2BTVG",
        'RestaurantName': "NU Kitchen Somerville",
        'Price': "14.46",
        'OrderStatus': "Completed",
    },
]

